name: docker4640

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push frontend image 
        uses: docker/build-push-action@v3
        with:
            context: frontend
            push: true
            tags: stevencchang/4640frontend:latest  # ADJUST WITH YOUR USER NAME
      - name: Build and push backend image 
        uses: docker/build-push-action@v3
        with:
            context: backend
            push: true
            tags: stevencchang/4640frontend:latest  # ADJUST WITH YOUR USER NAME
      